[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/SpideyZac/mog"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
missing_docs_in_private_items = "deny"
absolute_paths = "deny"
doc_markdown = "warn"
missing_panics_doc = "warn"
missing_errors_doc = "warn"
undocumented_unsafe_blocks = "warn"

[workspace.dependencies]
anyhow = "1"
arboard = "3"
clap = { version = "4", features = ["derive"] }
crossterm = { version = "0.29", features = ["event-stream"] }
discord-rich-presence = "1"
dirs = "7"
flate2 = "1"
futures = "0.3"
ignore = "0.4"
lsp-types = "0.97"
minisign-verify = "0.3"
mog-ai = { path = "crates/mog-ai" }
mog-audio = { path = "crates/mog-audio" }
mog-config = { path = "crates/mog-config" }
mog-core = { path = "crates/mog-core" }
mog-flair = { path = "crates/mog-flair" }
mog-git = { path = "crates/mog-git" }
mog-lsp = { path = "crates/mog-lsp" }
mog-syntax = { path = "crates/mog-syntax" }
mog-term = { path = "crates/mog-term" }
mog-tui = { path = "crates/mog-tui" }
notify = "8"
open = "5"
portable-pty = "0.9"
ratatui = "0.30"
rodio = { version = "0.22", default-features = false, features = ["playback"] }
reqwest = { version = "0.13", features = ["json"] }
regex = "1"
ropey = "1.6"
serde = { version = "1", features = ["derive"] }
self-replace = "1.5"
serde_json = "1"
sha2 = "0.10"
similar = "3"
sysinfo = { version = "0.39", default-features = false, features = ["system"] }
thiserror = "2"
tar = "0.4"
tokio = { version = "1", features = ["full"] }
tree-sitter-bash = "0.25"
tree-sitter-c = "0.24"
tree-sitter-c-sharp = "0.23"
tree-sitter-cpp = "0.23"
tree-sitter-css = "0.25"
tree-sitter-elixir = "0.3"
tree-sitter-haskell = "0.24"
tree-sitter-html = "0.23"
tree-sitter-java = "0.23"
tree-sitter-lua = "0.5"
tree-sitter-make = "1.1"
tree-sitter-ocaml = "0.26"
tree-sitter-php = "0.24"
tree-sitter-powershell = "0.26"
tree-sitter-ruby = "0.23"
tree-sitter-scala = "0.26"
tree-sitter-sequel = "0.3"
tree-sitter-swift = "0.7"
tree-sitter-xml = "0.7"
tree-sitter-yaml = "0.7"
tree-sitter-zig = "1.1"
tree-sitter-vue3 = { package = "octorus-tree-sitter-vue3", version = "0.1" }
tree-sitter-go = "0.25"
tree-sitter-highlight = "0.27"
tree-sitter-javascript = "0.25"
tree-sitter-json = "0.24"
tree-sitter-md = "0.5"
tree-sitter-python = "0.25"
tree-sitter-rust = "0.24"
tree-sitter-toml-ng = "0.7"
tree-sitter-typescript = "0.23"
toml = "1"
toml_edit = "0.25"
unicode-width = "0.2"
vt100 = "0.16"
zip = { version = "8", default-features = false, features = ["deflate-flate2"] }
