[package]
name = "mog-tui"
description = "The terminal user interface of mog."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crossterm.workspace = true
mog-config.workspace = true
mog-core.workspace = true
mog-git.workspace = true
ratatui.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
