[package]
name = "mog"
description = "A terminal code editor that mogs other editors."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
arboard.workspace = true
clap.workspace = true
mog-ai.workspace = true
mog-audio.workspace = true
lsp-types.workspace = true
mog-config.workspace = true
crossterm.workspace = true
discord-rich-presence.workspace = true
futures.workspace = true
mog-core.workspace = true
mog-flair.workspace = true
mog-git.workspace = true
mog-lsp.workspace = true
mog-term.workspace = true
mog-tui.workspace = true
notify.workspace = true
ratatui.workspace = true
tokio.workspace = true
