[package]
name = "mog-core"
description = "The editing model of mog."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ignore.workspace = true
regex.workspace = true
ropey.workspace = true
serde.workspace = true
unicode-width.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
