[package]
name = "mog-flair"
description = "The silly and cool extras drawn around the mog editor."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
crossterm.workspace = true
mog-audio.workspace = true
mog-core.workspace = true
mog-tui.workspace = true
ratatui.workspace = true
sysinfo.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
